default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: fix-encoding-pragma
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]
